# Generated by Django 5.1.5 on 2025-02-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='weevil_detected',
        ),
    ]
