# Generated by Django 5.1.5 on 2025-02-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_active_user_weevil_detected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weevil_detected',
            field=models.BooleanField(default=False),
        ),
    ]
